---
abstract: 'Keep up-to-date with Zabbix from the command line'
author:
  - 'Dominic Humphries <dominic@oneandoneis2.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.037
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Zabbix-Cli-Monitor
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  File::HomeDir: 0
  IO::Interactive: 0
  JSON: 0
  MooseX::App::Simple: 0
  Term::ANSIColor: 0
  YAML::XS: 0
  Zabbix::API: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/oneandoneis2/Zabbix-Cli-Monitor/issues
  homepage: https://github.com/oneandoneis2/Zabbix-Cli-Monitor
  repository: https://github.com/oneandoneis2/Zabbix-Cli-Monitor.git
version: 0.01
x_contributors:
  - 'Dominic Humphries <dominich@broadbean.com>'
